from django.urls import path
from django.contrib.auth.views import LogoutView 
from .views import *

urlpatterns = [
    path('', Inicio, name='Inicio'),
    path('Lista-nintendo/', Lista_DFJF_nintendo, name="Listanintnedo"),
    path('Lista-playstation/', Lista_DFJF_playstation, name="Listaplaystation"),
    path('Lista-xbox/', Lista_DFJF_xbox, name="Listaxbox"),
    path('Nintendo/', nintendo, name='Nintendo'),
    path('Playstation/', playstation, name='Playstation'),
    path('Xbox/', xbox, name='Xbox'),
    path('Links/', Links, name='Links'),
    path('NintendoFormulario/', nintendoFormulario, name='NintendoFormulario'),
    path('PlaystationFormulario/', playstationFormulario, name='PlaystationFormulario'),
    path('XboxFormulario/', xboxFormulario, name='XboxFormulario'),
    path('BuscardesarrolladorasNin/', BuscarDesarrolladorasNin, name='BuscarDesarrolladorasNin'),   
    path('BuscardesarrolladorasPlay/', BuscarDesarrolladorasPlay, name='BuscarDesarrolladorasPlay'),
    path('BuscardesarrolladorasXbox/', BuscarDesarrolladorasXbox, name='BuscarDesarrolladorasXbox'),
    path('BuscarNin/', BuscarNin, name='BuscarNin'),
    path('BuscarPlay/', BuscarPlay, name='BuscarPlay'),
    path('BuscarXbox/', BuscarXbox, name='BuscarXbox'),
    path('ListaXbox/', ListaXbox, name='ListaXbox'),
    path('ListaPlaystation/', ListaPlaystation, name='ListaPlaystation'),
    path('ListaNintendo/', ListaNintendo, name='ListaNintendo'),
    path('EliminarJuegoNin/<int:id>', eliminarJuegoNin, name='EliminarJuegoNin'),
    path('EliminarJuegoPlay/<int:id>', eliminarJuegoPlay, name='EliminarJuegoPlay'),
    path('EliminarJuegoXbox/<int:id>', eliminarJuegoXbox, name='EliminarJuegoXbox'),
    path('EditarJuegoXbox/<int:id>', EditarJuegoXbox, name='EditarJuegoXbox'),
    path('EditarJuegoPlay/<int:id>', EditarJuegoPlay, name='EditarJuegoPlay'),
    path('EditarJuegoNin/<int:id>', EditarJuegoNin, name='EditarJuegoNin'),
    path('Nintendo_List/', NintendoList.as_view(), name='Nintendo_List'),
    path('Nintendo_Detail/<pk>', NintendoDetail.as_view(), name='Nintendo_Detail'),
    path('Nintendo_Create/', NintendoCreate.as_view(), name='Nintendo_Create'),
    path('Nintendo_Update/<pk>', NintendoUpdate.as_view(), name='Nintendo_Update'),
    path('Nintendo_Delete/<pk>', NintendoDelete.as_view(), name='Nintendo_Delete'),
    path('Playstation_List/', PlaystationList.as_view(), name='Playstation_List'),
    path('Playstation_Detail/<pk>', PlaystationDetail.as_view(), name='Playstation_Detail'),
    path('Playstation_Create/', PlaystationCreate.as_view(), name='Playstation_Create'),
    path('Playstation_Update/<pk>', PlaystationUpdate.as_view(), name='Playstation_Update'),
    path('Playstation_Delete/<pk>', PlaystationDelete.as_view(), name='Playstation_Delete'),
    path('Xbox_List/', XboxList.as_view(), name='Xbox_List'),
    path('Xbox_Detail/<pk>', XboxDetail.as_view(), name='Xbox_Detail'),
    path('Xbox_Create/', XboxCreate.as_view(), name='Xbox_Create'),
    path('Xbox_Update/<pk>', XboxUpdate.as_view(), name='Xbox_Update'),
    path('Xbox_Delete/<pk>', XboxDelete.as_view(), name='Xbox_Delete'),
    path('Login/', Login, name='Login'),
    path('Register/', register, name='Register'),
    path('Logout/', LogoutView.as_view(template_name="Logout.html"), name='Logout'),
    path('EditarPerfil/', EditarPerfil, name="EditarPerfil"),
    path('Agregar_avatar/', Agregar_avatar, name='Agregar_avatar'),
]