# Generated by Django 4.2.4 on 2023-09-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nintendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desarrolladora', models.CharField(max_length=60)),
                ('Fecha_de_inauguración', models.DateField()),
                ('Juego', models.CharField(max_length=50)),
                ('Fecha_de_salida', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Playstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desarrolladora', models.CharField(max_length=60)),
                ('Fecha_de_inauguración', models.DateField()),
                ('Juego', models.CharField(max_length=50)),
                ('Fecha_de_salida', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Xbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desarrolladora', models.CharField(max_length=60)),
                ('Fecha_de_inauguración', models.DateField()),
                ('Juego', models.CharField(max_length=50)),
                ('Fecha_de_salida', models.DateField()),
            ],
        ),
    ]
